couchdb:
  image: topmonks/couchdb
  environment:
    - ADMIN_USERNAME=admin
    - ADMIN_PASSWORD=admin
    - COMPACTIONS_DEFAULT=[{db_fragmentation, "70%"}, {view_fragmentation, "60%"}, {from, "20:00"}, {to, "23:59"}]
  volumes:
    - ./data:/var/lib/couchdb
  ports:
    - "5984:5984"
